WHITELISTED_IAM_USERS = "thor|odin|thien"
WHITELISTED_IAM_ROLES = "thor|odin|thien"

WHITELISTED_IAM_USERS_VARIABLE = "WHITELISTED_IAM_USERS"
WHITELISTED_IAM_ROLES_VARIABLE = "WHITELISTED_IAM_ROLES"

BUCKET_NAME = "iam-keeper-state-oesckmpcqeayxfxbxazs"
