check:
  pre-commit run --all-files

unit-filter PATTERN CASE:
  pytest tests/unit/{{PATTERN}} -k {{CASE}}

unit-test PATTERN:
  pytest tests/unit/{{PATTERN}}

unit-tests:
  pytest tests/unit

integration-tests:
  pytest tests/integration

update_requirements:
  pip-compile requirements.in
  cp requirements.txt lambda_func/requirements.txt
