check:
  pre-commit run --all-files

filter PATTERN CASE:
  pytest tests/{{PATTERN}} -k {{CASE}}

test:
  pytest tests

update_requirements:
  pip-compile requirements.in
  cp requirements.txt iam_event_handler/requirements.txt
  cp requirements.txt policy_snapshot/requirements.txt
