check:
  pre-commit run --all-files

filter PATTERN CASE:
  pytest tests/{{PATTERN}} -k {{CASE}}

test PATTERN:
  pytest tests/{{PATTERN}}

tests:
  pytest tests

update_requirements:
  pip-compile requirements.in
  cp requirements.txt lambda_func/requirements.txt
